// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpWYtZGZqq4mAviSjhLl2ILyyWJIw-wC0',
    appId: '1:541071911304:web:f69b14a4c70c0b6f61723d',
    messagingSenderId: '541071911304',
    projectId: 'ftb-personalnotes',
    authDomain: 'ftb-personalnotes.firebaseapp.com',
    storageBucket: 'ftb-personalnotes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUA7mMj4b_jjkl929cRExAQVNWuGxK1kY',
    appId: '1:541071911304:android:6af0dc752590b9ca61723d',
    messagingSenderId: '541071911304',
    projectId: 'ftb-personalnotes',
    storageBucket: 'ftb-personalnotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYlIAJ6JklJd8UociRzYXNgaIWKrD6ask',
    appId: '1:541071911304:ios:7cb1f522a63e317f61723d',
    messagingSenderId: '541071911304',
    projectId: 'ftb-personalnotes',
    storageBucket: 'ftb-personalnotes.appspot.com',
    iosClientId: '541071911304-q40g7bf6ls5japhdfv1cjqf95hdtd9lq.apps.googleusercontent.com',
    iosBundleId: 'me.favoritetechbro.personalnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYlIAJ6JklJd8UociRzYXNgaIWKrD6ask',
    appId: '1:541071911304:ios:7cb1f522a63e317f61723d',
    messagingSenderId: '541071911304',
    projectId: 'ftb-personalnotes',
    storageBucket: 'ftb-personalnotes.appspot.com',
    iosClientId: '541071911304-q40g7bf6ls5japhdfv1cjqf95hdtd9lq.apps.googleusercontent.com',
    iosBundleId: 'me.favoritetechbro.personalnotes',
  );
}
